databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "make start"
    envVars:
      - key: DATABASE_URL
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
